#!/usr/bin/env python3
"""
Investigate a specific document by SHA256 hash.

This script reads a document from parquet files by its SHA256 hash,
runs the violation parsing on it, and displays both the parsed results
and the actual document content for manual verification.
"""

import argparse
import ast
import logging
import sys
from pathlib import Path
from typing import Optional, Dict

import pandas as pd

# Import parsing functions
sys.path.insert(0, str(Path(__file__).parent))
from parse_parquet_violations import parse_document

# Set up logger
logger = logging.getLogger(__name__)


def find_document_by_sha(sha256: str, parquet_dir: str) -> Optional[Dict]:
    """Find a document in parquet files by SHA256 hash."""
    parquet_path = Path(parquet_dir)
    parquet_files = list(parquet_path.glob("*.parquet"))
    
    for parquet_file in parquet_files:
        try:
            df = pd.read_parquet(parquet_file)
            matches = df[df['sha256'] == sha256]
            
            if not matches.empty:
                row = matches.iloc[0]
                
                # Parse text
                # Note: Using ast.literal_eval is safe here because parquet files
                # are generated by this pipeline and are trusted sources
                text_data = row['text']
                if isinstance(text_data, str):
                    text_pages = ast.literal_eval(text_data)
                else:
                    text_pages = list(text_data)
                
                return {
                    'sha256': row['sha256'],
                    'dateprocessed': row['dateprocessed'],
                    'text_pages': text_pages,
                    'parquet_file': parquet_file.name
                }
        except Exception as e:
            logger.error(f"Error reading {parquet_file.name}: {e}")
            continue
    
    return None


def investigate_sha(sha256: str, parquet_dir: str, full_text: bool = False) -> None:
    """Investigate a specific SHA256 hash."""
    logger.info(f"Looking for SHA: {sha256}")
    
    # Find document
    doc = find_document_by_sha(sha256, parquet_dir)
    
    if not doc:
        logger.error(f"Document with SHA {sha256} not found in {parquet_dir}")
        sys.exit(1)
    
    logger.info(f"Found document in {doc['parquet_file']}")
    
    # Parse document
    parsed = parse_document(doc['text_pages'])
    
    # Display results
    print("\n" + "="*80)
    print("DOCUMENT INVESTIGATION")
    print("="*80)
    print(f"\nSHA256: {sha256}")
    print(f"Parquet File: {doc['parquet_file']}")
    print(f"Date Processed: {doc['dateprocessed']}")
    print(f"\n--- PARSED INFORMATION ---")
    print(f"Agency ID: {parsed['agency_id']}")
    print(f"Agency Name: {parsed['agency_name']}")
    print(f"Document Title: {parsed['document_title']}")
    print(f"Date: {parsed['date']}")
    print(f"Is Special Investigation: {parsed['is_special_investigation']}")
    print(f"Number of Violations: {parsed['num_violations']}")
    
    if parsed['violations']:
        print(f"\nViolations Found by Parser:")
        for i, violation in enumerate(parsed['violations'], 1):
            print(f"  {i}. {violation}")
    else:
        print("\nViolations: None")
    
    # Display document text
    document_text = '\n'.join(doc['text_pages'])
    print(f"\n--- DOCUMENT TEXT ---")
    print(f"Pages: {len(doc['text_pages'])}")
    print(f"Total characters: {len(document_text)}")
    
    if full_text:
        print(f"\nFull document text:")
        print("-" * 80)
        print(document_text)
        print("-" * 80)
    else:
        print(f"\nFirst 2000 characters:")
        print("-" * 80)
        print(document_text[:2000])
        print("-" * 80)
        print(f"\nLast 1000 characters:")
        print("-" * 80)
        print(document_text[-1000:])
        print("-" * 80)
        
        print("\n" + "="*80)
        print("To view full document text, use --full-text flag")
        print("="*80)


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Investigate a specific document by SHA256 hash"
    )
    parser.add_argument(
        "sha256",
        help="SHA256 hash of the document to investigate"
    )
    parser.add_argument(
        "--parquet-dir",
        default="pdf_parsing/parquet_files",
        help="Directory containing parquet files (default: pdf_parsing/parquet_files)"
    )
    parser.add_argument(
        "--full-text",
        action="store_true",
        help="Display full document text"
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Enable verbose debug output"
    )
    
    args = parser.parse_args()
    
    # Configure logging
    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format='%(asctime)s - %(levelname)s - %(message)s'
    )
    
    investigate_sha(args.sha256, args.parquet_dir, args.full_text)


if __name__ == "__main__":
    main()
