import React from 'react';
import { KeywordBadgeList } from './KeywordBadge.jsx';
import { getViolationLevelStyle, escapeHtml } from '../utils/helpers.js';

/**
 * DocumentItem component for displaying a single document in a list
 * @param {Object} props
 * @param {Object} props.document - Document data object
 * @param {string} props.baseUrl - Base URL for links
 * @param {Function} [props.onCopyLink] - Callback when copy link is clicked
 */
export function DocumentItem({ document: doc, baseUrl, onCopyLink }) {
    const displayTitle = doc.document_title || doc.agency_name || 'Untitled Document';
    const isSir = doc.is_special_investigation;
    const hasSummary = doc.sir_summary && doc.sir_summary.summary;
    const hasViolationLevel = doc.sir_violation_level && doc.sir_violation_level.level;

    // Get violation level styling
    const violationLevelBadge = hasViolationLevel ? (
        <span style={getViolationLevelStyle(doc.sir_violation_level.level)}>
            {getViolationLevelEmoji(doc.sir_violation_level.level)} {capitalizeFirst(doc.sir_violation_level.level)}
        </span>
    ) : null;

    const handleCopyLink = (e) => {
        e.stopPropagation();
        if (onCopyLink && doc.sha256) {
            onCopyLink(doc.sha256, e);
        }
    };

    return (
        <div className={`document-item ${isSir ? 'is-sir' : ''}`}>
            <div style={{ fontWeight: 600, marginBottom: '4px' }}>
                {displayTitle}
                {isSir && <span style={{ color: '#e74c3c', fontSize: '0.85em' }}> 🔍 SIR</span>}
                {doc.sha256 && (
                    <button 
                        className="copy-link-btn" 
                        onClick={handleCopyLink}
                        title="Copy link to this document"
                    >
                        🔗
                    </button>
                )}
            </div>
            <div className="date">{doc.date || 'Date not specified'}</div>
            
            {hasSummary && (
                <div style={{
                    marginTop: '10px',
                    padding: '10px',
                    background: '#fff9e6',
                    borderLeft: '3px solid #f39c12',
                    borderRadius: '4px'
                }}>
                    <div style={{ fontWeight: 600, color: '#e67e22', marginBottom: '6px', fontSize: '0.9em' }}>
                        📋 Summary (AI-generated by DeepSeek v3.2)
                        {doc.sir_summary.violation === 'y' && (
                            <span style={{ color: '#e74c3c', marginLeft: '6px' }}>
                                ⚠️ Violation Substantiated{violationLevelBadge}
                            </span>
                        )}
                        {doc.sir_summary.violation === 'n' && (
                            <span style={{ color: '#27ae60', marginLeft: '6px' }}>✓ No Violation</span>
                        )}
                    </div>
                    <div style={{ fontSize: '0.9em', lineHeight: 1.5, color: '#555' }}>
                        {doc.sir_summary.summary}
                    </div>
                    {hasViolationLevel && doc.sir_violation_level.keywords?.length > 0 && (
                        <div style={{ marginTop: '8px' }}>
                            <KeywordBadgeList 
                                keywords={doc.sir_violation_level.keywords} 
                                maxDisplay={5}
                                small
                            />
                        </div>
                    )}
                </div>
            )}
            
            {doc.sha256 && (
                <div style={{ marginTop: '8px' }}>
                    <a 
                        href={`${baseUrl}document.html?sha=${doc.sha256}`}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="view-document-btn"
                        style={{ textDecoration: 'none', display: 'inline-block' }}
                    >
                        📄 View Full Document
                    </a>
                </div>
            )}
        </div>
    );
}

/**
 * DocumentList component for displaying a list of documents
 * @param {Object} props
 * @param {Array} props.documents - Array of document objects
 * @param {number} [props.filteredOutCount] - Number of documents filtered out
 * @param {string} props.baseUrl - Base URL for links
 * @param {Function} [props.onCopyLink] - Callback when copy link is clicked
 */
export function DocumentList({ documents, filteredOutCount = 0, baseUrl, onCopyLink }) {
    if (!documents || documents.length === 0) {
        const noDocsMessage = filteredOutCount > 0 ? (
            <p style={{
                color: '#e67e22',
                background: '#fff3cd',
                padding: '12px',
                borderRadius: '4px',
                borderLeft: '3px solid #f39c12'
            }}>
                <strong>All {filteredOutCount} {filteredOutCount === 1 ? 'report' : 'reports'} have been filtered out.</strong><br />
                <span style={{ fontSize: '0.9em' }}>Try adjusting the filters above to see more reports.</span>
            </p>
        ) : (
            <p style={{ color: '#666' }}>No reports available.</p>
        );

        return (
            <div className="documents-list">
                <div className="section-title">Documents & Reports</div>
                {noDocsMessage}
            </div>
        );
    }

    // Sort by date (most recent first)
    const sortedDocuments = [...documents].sort((a, b) => {
        return new Date(b.date) - new Date(a.date);
    });

    return (
        <div className="documents-list">
            <div className="section-title">Documents & Reports ({documents.length})</div>
            {sortedDocuments.map((doc, index) => (
                <DocumentItem 
                    key={doc.sha256 || index}
                    document={doc}
                    baseUrl={baseUrl}
                    onCopyLink={onCopyLink}
                />
            ))}
        </div>
    );
}

// Helper functions
function getViolationLevelEmoji(level) {
    const levelLower = level?.toLowerCase();
    if (levelLower === 'low') return '🟡';
    if (levelLower === 'moderate') return '🟠';
    if (levelLower === 'severe') return '🔴';
    return '⚪';
}

function capitalizeFirst(str) {
    if (!str) return '';
    return str.charAt(0).toUpperCase() + str.slice(1).toLowerCase();
}

export default DocumentItem;
